# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0002_auto_20170729_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='charge_id',
            field=models.CharField(default=12312312312, max_length=234),
            preserve_default=False,
        ),
    ]
